# Generated by Django 3.2.9 on 2021-12-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
