# Generated by Django 3.2.9 on 2021-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0005_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
